package com.example.mikeherich1.tut12;

/**
 * Created by mikeherich1 on 08.05.15.
 */
public class SuperHeroInfo {

    public static final String[] NAMES = {"Superman", "Batman", "Wonder Woman", "Flash", "Green Lantern", "Aquaman", "Martian Manhunter",
                                            "Green Arrow"};

    public static final String[] HISTORY = {"He was born Kal-El on the planet Krypton, before \nbeing rocketed to Earth as an infant by his scientist father Jor-El, \nmoments before Krypton's destruction. Discovered and adopted by \na Kansas farmer and his wife, the child is raised as Clark Kent and imbued with \na strong moral compass. Very early on he started to display superhuman abilities, which, \nupon reaching maturity, he resolved to use for the benefit of humanity. \nSuperman resides and operates in the fictional American city of Metropolis. \nAs Clark Kent, he is a journalist for the Daily Planet, a Metropolis newspaper. \nSuperman's primary love interest is Lois Lane, and his archenemy is supervillain Lex Luthor.",
                                            "Batman's secret identity is Bruce Wayne, an American billionaire\n, industrialist, and philanthropist. Having witnessed the murder \nof his parents as a child, he swore revenge on criminals, an oath \ntempered with a sense of justice. Wayne trains himself both physically \nand intellectually and dons a bat-themed costume to fight crime.",
                                            "She is a warrior princess of the Amazons (based on the Amazons of Greek mythology) \nand is known in her homeland as Princess Diana of Themyscira. \nWhen outside her homeland, she is sometimes known \nby the secret identity Diana Prince. She is gifted with a wide range of \nsuperhuman powers and superior combat and battle skills. She possesses an arsenal \nof weapons, including the Lasso of Truth, a pair of indestructible bracelets,\na tiara which serves as a projectile, and, in some stories, an invisible \nairplane, Mental Radio, and Purple Ray that could heal otherwise lethal injuries.",
                                            "Gay Garrick was a college student in 1938 who accidentally inhaled \nheavy water vapors after taking a smoke break inside his laboratory\n where he had been working.[8] As a result, he found that he could\nrun at superhuman speed and had similarly fast reflexes. After a brief \ncareer as a college football star, he donned a red shirt with a lightning bolt \nand a stylized metal helmet with wings (based on images of the Greek deity \nHermes), and began to fight crime as the Flash. His first case involved \nbattling the \"Faultless Four\", a group of blackmailers. \nGarrick kept his identity secret for years without a mask by continually \nvibrating his body while in public so that any photograph of his face\nwould be blurred. Although originally from Earth-Two, he was incorporated\ninto the history of New Earth following the Crisis on Infinite Earths \nand is still active as the Flash operating out of Keystone City. \nHe is a member of the Justice Society.",
                                            "This Green Lantern's real name was Alan Scott, a railroad \nengineer who, after a railway crash, came into possession of a magic \nlantern which spoke to him and said it would bring power. \nFrom this, he crafted a magic ring which gave him a wide variety of powers. \nThe limitations of the ring were that it had to be \"charged\" every 24 hours \nby touching it to the lantern for a time, and that it \ndid not work on objects made of wood.",
                                            "In his early Golden Age appearances, Aquaman could breathe underwater \nand control fish and other underwater life for up to a minute.\nInitially, he was depicted as speaking to sea creatures \"in their own language\" rather \nthan telepathically, and only when they were close enough \nto hear him (within a 20-yard radius). Aquaman's adventures took place all across the world, \nand his base was \"a wrecked fishing boat kept underwater,\" in which he lived",
                                            "In 1972, Superman was teleported to New Mars.[14] J'onzz briefly returned \nto Earth by spaceship in 1975.[15] J'onn made another trip to Earth \nshortly thereafter,[16] leading to Superman and Batman fighting alongside him on New Mars.\nThree years later, he was discovered playing cosmic-level chess with Despero, \nusing JLA-ers as the pieces.[18] The Martian again \nencountered Superman in outer space.",
                                            "Green Arrow was one of the few DC characters to keep going after the Golden Age \nof Comic Books. The longevity of the character was due to the influence \nof creator Mort Weisinger, who kept Green Arrow and Aquaman as \nback-up features to the headlining Superboy feature, first \nin More Fun Comics and then Adventure Comics."
                                            };

}
